[2023-07-25T22:42:56.644-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T13:45:00+00:00 [queued]>
[2023-07-25T22:42:56.653-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T13:45:00+00:00 [queued]>
[2023-07-25T22:42:56.653-0300] {taskinstance.py:1308} INFO - Starting attempt 74 of 77
[2023-07-25T22:42:56.674-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-25 13:45:00+00:00
[2023-07-25T22:42:56.679-0300] {standard_task_runner.py:57} INFO - Started process 185284 to run task
[2023-07-25T22:42:56.684-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'scheduled__2023-07-25T13:45:00+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmpxvp1l1xe']
[2023-07-25T22:42:56.685-0300] {standard_task_runner.py:85} INFO - Job 319: Subtask extract_write_local
[2023-07-25T22:42:56.736-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T13:45:00+00:00 [running]> on host ubuntu
[2023-07-25T22:42:56.809-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-25T13:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='74' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-25T13:45:00+00:00'
[2023-07-25T22:42:56.837-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 72, in extract_write_local
    extract_write_postgres(date)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 55, in extract_write_postgres
    cursor.execute(f'SELECT * FROM {table};')
NameError: name 'cursor' is not defined
[2023-07-25T22:42:56.845-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230725T134500, start_date=20230726T014256, end_date=20230726T014256
[2023-07-25T22:42:56.861-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 319 for task extract_write_local (name 'cursor' is not defined; 185284)
[2023-07-25T22:42:56.896-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-25T22:42:56.922-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
