[2023-07-25T11:13:42.975-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T12:45:00+00:00 [queued]>
[2023-07-25T11:13:42.981-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T12:45:00+00:00 [queued]>
[2023-07-25T11:13:42.981-0300] {taskinstance.py:1308} INFO - Starting attempt 8 of 11
[2023-07-25T11:13:43.001-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-25 12:45:00+00:00
[2023-07-25T11:13:43.005-0300] {standard_task_runner.py:57} INFO - Started process 41101 to run task
[2023-07-25T11:13:43.009-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'scheduled__2023-07-25T12:45:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmp1u7bg_fa']
[2023-07-25T11:13:43.010-0300] {standard_task_runner.py:85} INFO - Job 62: Subtask extract_write_local
[2023-07-25T11:13:43.068-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T12:45:00+00:00 [running]> on host ubuntu
[2023-07-25T11:13:43.164-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-25T12:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-25T12:45:00+00:00'
[2023-07-25T11:13:43.191-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 95, in extract_write_local
    extract_write_postgres(date)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 79, in extract_write_postgres
    folder = f'/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/data/postgres/{table}/' + date_postgres.strftime('%Y-%m-%d')
AttributeError: 'str' object has no attribute 'strftime'
[2023-07-25T11:13:43.198-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230725T124500, start_date=20230725T141342, end_date=20230725T141343
[2023-07-25T11:13:43.215-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 62 for task extract_write_local ('str' object has no attribute 'strftime'; 41101)
[2023-07-25T11:13:43.221-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-25T11:13:43.240-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
