[2023-07-24T21:04:02.464-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T20:45:00+00:00 [queued]>
[2023-07-24T21:04:02.473-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T20:45:00+00:00 [queued]>
[2023-07-24T21:04:02.474-0300] {taskinstance.py:1308} INFO - Starting attempt 5 of 8
[2023-07-24T21:04:02.497-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-24 20:45:00+00:00
[2023-07-24T21:04:02.501-0300] {standard_task_runner.py:57} INFO - Started process 24221 to run task
[2023-07-24T21:04:02.505-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'scheduled__2023-07-24T20:45:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmpl3_5kiut']
[2023-07-24T21:04:02.506-0300] {standard_task_runner.py:85} INFO - Job 28: Subtask extract_write_local
[2023-07-24T21:04:02.582-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T20:45:00+00:00 [running]> on host ubuntu
[2023-07-24T21:04:02.702-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-24T20:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-24T20:45:00+00:00'
[2023-07-24T21:04:02.739-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 56, in extract_write_local
    extract_write_postgres()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 44, in extract_write_postgres
    folder = '/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/data/postgres/' + '{table}/' + date.strftime('%Y-%m-%d')
NameError: name 'date' is not defined
[2023-07-24T21:04:02.747-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230724T204500, start_date=20230725T000402, end_date=20230725T000402
[2023-07-24T21:04:02.768-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task extract_write_local (name 'date' is not defined; 24221)
[2023-07-24T21:04:02.810-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-24T21:04:02.833-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
