[2023-07-24T18:48:20.138-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T20:45:00+00:00 [queued]>
[2023-07-24T18:48:20.144-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T20:45:00+00:00 [queued]>
[2023-07-24T18:48:20.145-0300] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2023-07-24T18:48:20.164-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-24 20:45:00+00:00
[2023-07-24T18:48:20.167-0300] {standard_task_runner.py:57} INFO - Started process 20706 to run task
[2023-07-24T18:48:20.171-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'scheduled__2023-07-24T20:45:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmps36xhxdu']
[2023-07-24T18:48:20.172-0300] {standard_task_runner.py:85} INFO - Job 18: Subtask extract_write_local
[2023-07-24T18:48:20.228-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T20:45:00+00:00 [running]> on host ubuntu
[2023-07-24T18:48:20.297-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-24T20:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-24T20:45:00+00:00'
[2023-07-24T18:48:20.299-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 54, in extract_write_local
    extract_write_csv()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 11, in extract_write_csv
    date = kwargs['execution_date']
KeyError: 'execution_date'
[2023-07-24T18:48:20.303-0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230724T204500, start_date=20230724T214820, end_date=20230724T214820
[2023-07-24T18:48:20.319-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task extract_write_local ('execution_date'; 20706)
[2023-07-24T18:48:20.342-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-24T18:48:20.367-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
