[2023-07-26T11:49:17.672-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local manual__2023-07-26T14:23:45.992019+00:00 [queued]>
[2023-07-26T11:49:17.679-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local manual__2023-07-26T14:23:45.992019+00:00 [queued]>
[2023-07-26T11:49:17.680-0300] {taskinstance.py:1308} INFO - Starting attempt 9 of 9
[2023-07-26T11:49:17.698-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-26 14:23:45.992019+00:00
[2023-07-26T11:49:17.703-0300] {standard_task_runner.py:57} INFO - Started process 22648 to run task
[2023-07-26T11:49:17.707-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'manual__2023-07-26T14:23:45.992019+00:00', '--job-id', '419', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmpy8p4tf16']
[2023-07-26T11:49:17.707-0300] {standard_task_runner.py:85} INFO - Job 419: Subtask extract_write_local
[2023-07-26T11:49:17.749-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local manual__2023-07-26T14:23:45.992019+00:00 [running]> on host ubuntu
[2023-07-26T11:49:17.823-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T14:23:45.992019+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-26T14:23:45.992019+00:00'
[2023-07-26T11:49:17.832-0300] {logging_mixin.py:150} WARNING - /home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-26T11:49:17.832-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 83, in extract_write_local
    date = datetime.strptime(execution_date, '%Y-%m-%d') if execution_date else kwargs['execution_date']
TypeError: strptime() argument 1 must be str, not Proxy
[2023-07-26T11:49:17.837-0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230726T142345, start_date=20230726T144917, end_date=20230726T144917
[2023-07-26T11:49:17.852-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 419 for task extract_write_local (strptime() argument 1 must be str, not Proxy; 22648)
[2023-07-26T11:49:17.878-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-26T11:49:17.905-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
