[2023-07-24T21:11:58.773-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T22:45:00+00:00 [queued]>
[2023-07-24T21:11:58.779-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T22:45:00+00:00 [queued]>
[2023-07-24T21:11:58.780-0300] {taskinstance.py:1308} INFO - Starting attempt 6 of 8
[2023-07-24T21:11:58.800-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-24 22:45:00+00:00
[2023-07-24T21:11:58.804-0300] {standard_task_runner.py:57} INFO - Started process 25805 to run task
[2023-07-24T21:11:58.808-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'scheduled__2023-07-24T22:45:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmp54jtsp7e']
[2023-07-24T21:11:58.808-0300] {standard_task_runner.py:85} INFO - Job 38: Subtask extract_write_local
[2023-07-24T21:11:58.862-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T22:45:00+00:00 [running]> on host ubuntu
[2023-07-24T21:11:58.962-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-24T22:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-24T22:45:00+00:00'
[2023-07-24T21:11:58.973-0300] {logging_mixin.py:150} WARNING - /home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-24T21:12:00.255-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 41, in extract_write_local
    cursor.execute(f'SELECT * FROM {table};')
psycopg2.errors.UndefinedTable: relation "information_schema_catalog_name" does not exist
LINE 1: SELECT * FROM information_schema_catalog_name;
                      ^

[2023-07-24T21:12:00.260-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230724T224500, start_date=20230725T001158, end_date=20230725T001200
[2023-07-24T21:12:00.278-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task extract_write_local (relation "information_schema_catalog_name" does not exist
LINE 1: SELECT * FROM information_schema_catalog_name;
                      ^
; 25805)
[2023-07-24T21:12:00.302-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-24T21:12:00.321-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
