[2023-07-24T21:30:29.947-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T22:45:00+00:00 [queued]>
[2023-07-24T21:30:29.956-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T22:45:00+00:00 [queued]>
[2023-07-24T21:30:29.957-0300] {taskinstance.py:1308} INFO - Starting attempt 15 of 18
[2023-07-24T21:30:29.979-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-24 22:45:00+00:00
[2023-07-24T21:30:29.984-0300] {standard_task_runner.py:57} INFO - Started process 29262 to run task
[2023-07-24T21:30:29.989-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'scheduled__2023-07-24T22:45:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmpfgumc1pk']
[2023-07-24T21:30:29.989-0300] {standard_task_runner.py:85} INFO - Job 48: Subtask extract_write_local
[2023-07-24T21:30:30.040-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-24T22:45:00+00:00 [running]> on host ubuntu
[2023-07-24T21:30:30.115-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-24T22:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='15' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-24T22:45:00+00:00'
[2023-07-24T21:30:30.118-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 92, in extract_write_local
    extract_write_postgres()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 59, in extract_write_postgres
    date = kwargs['execution_date']
KeyError: 'execution_date'
[2023-07-24T21:30:30.123-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230724T224500, start_date=20230725T003029, end_date=20230725T003030
[2023-07-24T21:30:30.139-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task extract_write_local ('execution_date'; 29262)
[2023-07-24T21:30:30.162-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-24T21:30:30.183-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
